USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/ALCATEL/4032A/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6572
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := 4032A

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 20971520
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 20971520
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 545259520
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824
BOARD_FLASH_BLOCK_SIZE := 512
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_MTK := true 
BOARD_NEEDS_MTK_GETSIZE := true

RECOVERY_VARIANT := carliv

TARGET_PREBUILT_KERNEL := device/ALCATEL/4032A/prebuilt/kernel
TARGET_RECOVERY_INITRC := device/ALCATEL/4032A/recovery/init.mt6572.rc
TARGET_RECOVERY_FSTAB := device/ALCATEL/4032A/recovery/recovery.fstab

BOARD_HAS_NO_SELECT_BUTTON := true

BOARD_CUSTOM_BOOTIMG_MK := device/ALCATEL/4032A/mkmtkbootimg.mk

DEVICE_RESOLUTION := 480x800
